### PR TITLE
add spdlog 0.10.0

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by jpakkane** [comment]
Please add the license to `project`.

**Comment by agauniyal** [comment]
@jpakkane updated.

**Comment by agauniyal** [comment]
Huh, does it takes time to populate in wrapdb? It's still not visible..
Not even visible via api - https://wrapdb.mesonbuild.com/spdlog

**Comment by jpakkane** [comment]
The MR was missing `upstream.wrap`. I'll reset, then file a new mr.

**Comment by agauniyal** [comment]
Ah so sorry for that, there's a new release for it - https://github.com/gabime/spdlog/releases/latest

If it helps, just delete this branch and I'll file an proper MR with `upstream.wrap` for 0.11.0 since I'm eventually gonna use that.

**Comment by agauniyal** [comment]
@jpakkane - https://github.com/agauniyal/spdlog/tree/0.11.0

Do tell if I'm missing anything 😄

**Pull request merged**
